name: test-workflow
on:
  pull_request:
    branches:
    - main
    
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        uses: actions/hello-world-javascript-action@main
          with:
            who-to-greet: 'Mona the Octocat'```