name: SmartTrader Test Workflow

on: pull_request

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v4
      # setup nodejs environment
      - name: Setup Node.js environment
        uses: ./.github/actions/setup_node
      # cache the dependencies to speed up the build and then install dependencies
      - name: Cache dependencies
        uses: ./.github/actions/npm_install_from_cache
      # build the react app
      - name: Build
        run: npm run build
      # run tests
      - name: Run tests
        run: npm run test -- --coverage
      # test coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
      # deploy the react app to github pages
